"""Add DiningHallSchedule

Revision ID: 1c16271a7100
Revises: 41bbd52bd00a
Create Date: 2013-12-22 23:34:10.837759

"""

# revision identifiers, used by Alembic.
revision = '1c16271a7100'
down_revision = '41bbd52bd00a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dining_hall_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dining_hall_id', sa.Integer(), nullable=True),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('date_begin', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('days_of_week', sa.String(), nullable=True),
    sa.Column('regular_schedule', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dining_hall_id'], ['dining_hall.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dining_hall_schedule')
    ### end Alembic commands ###
