"""Removing station rel

Revision ID: 2b5622fe8c50
Revises: 1c16271a7100
Create Date: 2013-12-27 12:15:25.087647

"""

# revision identifiers, used by Alembic.
revision = '2b5622fe8c50'
down_revision = '1c16271a7100'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dish', u'station_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column(u'station_id', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###
