"""Initial

Revision ID: 41a1b36c3be8
Revises: None
Create Date: 2013-12-22 16:31:31.710890

"""

# revision identifiers, used by Alembic.
revision = '41a1b36c3be8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dining_hall',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('menu_url', sa.String(), nullable=True),
    sa.Column('page_str', sa.String(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('dining_hall_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dining_hall_id'], ['dining_hall.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###

    table = sa.sql.table("dining_hall",
        sa.sql.column("id", sa.Integer),
        sa.sql.column("name", sa.String),
        sa.sql.column("menu_url", sa.String),
        sa.sql.column("page_str", sa.String),
        sa.sql.column("org_id", sa.String),
    )
    op.bulk_insert(table, [
        { 
            'name': 'Danforth',
            'menu_url': 'http://www.campusdish.com/en-US/CSNE/Rochester/Menus/DanforthFreshFoodCompany.htm',
            'page_str': 'Danforth%20Fresh%20Food%20Company',
            'org_id': "195030",
        },
        { 
            'name': 'Douglass',
            'page_str': 'Douglass%20Dining%20Center',
            'menu_url': 'http://www.campusdish.com/en-US/CSNE/Rochester/Menus/DouglassDiningCenter.htm',
            'org_id': "195030",
        },
        { 
            'name': 'Commons',
            'menu_url': 'http://www.campusdish.com/en-US/CSNE/Rochester/Menus/DouglassDiningCenter.htm',
            'page_str': 'The%20Commons',
            'org_id': "195030",
        },
    ])


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_instance')
    op.drop_table('meal')
    op.drop_table('station')
    op.drop_table('dining_hall')
    ### end Alembic commands ###
