"""Adds station to dish_revision

Revision ID: 41bbd52bd00a
Revises: 5a7ae44e8571
Create Date: 2013-12-22 17:53:46.759010

"""

# revision identifiers, used by Alembic.
revision = '41bbd52bd00a'
down_revision = '5a7ae44e8571'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish_instance', sa.Column('station_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dish_instance', 'station_id')
    ### end Alembic commands ###
