"""Adding meal

Revision ID: 5a7ae44e8571
Revises: 2e0532ed8e9f
Create Date: 2013-12-22 17:45:46.724735

"""

# revision identifiers, used by Alembic.
revision = '5a7ae44e8571'
down_revision = '2e0532ed8e9f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'dish_instance', sa.Column('meal_id', sa.Integer(), nullable=True))
    op.drop_column(u'dish_instance', u'meal')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'dish_instance', sa.Column(u'meal', sa.VARCHAR(), nullable=True))
    op.drop_column(u'dish_instance', 'meal_id')
    op.drop_table('meal')
    ### end Alembic commands ###
